// config.js
const SUPABASE_URL = 'https://eorctlkxihvxynooadfg.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcmN0bGt4aWh2eHlub29hZGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxMTkzODIsImV4cCI6MjEwMjY5NTM4Mn0.SKeFWvo0DQymV_etSzl7C6ai_Om_tLaOuUraFI7MZzw';